# Generated by Django 5.2.3 on 2025-07-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='empresa',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
